BiletAl/Controllers/UyeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BiletAl.Models.Entity;
using PagedList;
using PagedList.Mvc;


namespace BiletAl.Controllers
{
    public class UyeController : Controller
    {
        // GET: Uye
        DBBILETALEntities1 db = new DBBILETALEntities1();
        public ActionResult Index(int sayfa=1)
        {
            var degerler = db.TBLKullanici.ToList();          
            return View(degerler);
        }
        [HttpGet]
        public ActionResult UyeEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UyeEkle(TBLKullanici p)
        {
            if (!ModelState.IsValid)
            {
                return View("UyeEkle");
            }
            db.TBLKullanici.Add(p);
            db.SaveChanges();
            return View();
        }
        public ActionResult UyeSil(int id)
        {
            var uye = db.TBLKullanici.Find(id);
            db.TBLKullanici.Remove(uye);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UyeGetir(int id)
        {
            var uye = db.TBLKullanici.Find(id);
            return View("UyeGetir", uye);
        }
        public ActionResult UyeGuncelle(TBLKullanici p)
        {
            var uye = db.TBLKullanici.Find(p.KullaniciID);
            uye.Ad = p.Ad;
            uye.Soyad = p.Soyad; 
            uye.Eposta = p.Eposta;
            uye.Parola = p.Parola;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
       
    }
}

BiletAl/Views/Uye/Index.cshtml
@using BiletAl.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TBLUYELER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<h2>Üyeler</h2>

@*@using (Html.BeginForm("Index", "Uye", FormMethod.Get))
{
    <div style="margin-top:15px; margin-bottom:15px;">
        <b>Aranacak Uye Adını Giriniz: </b> @Html.TextBox("p")
        <input type="submit" value="Ara" />
    </div>
}*@

<table class="table table-bordered">
    <tr>
        <th>ÜYE ID</th>
        <th>ÜYE ADI</th>
        <th>ÜYE SOYADI</th>
        <th>OKUL</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>KİTAP GEÇMİŞİ</th>
    </tr>
    @foreach (var uye in Model)
    {
<tr>
    <td>@uye.ID</td>
    <td>@uye.AD</td>
    <td>@uye.SOYAD</td>
    <td>@uye.OKUL</td>
    <td><a href="/Uye/UyeSil/@uye.ID" class="btn btn-danger">SİL</a></td>
    <td><a href="/Uye/UyeGetir/@uye.ID" class="btn btn-success">GÜNCELLE</a></td>
    <td><a href="/Uye/UyeKitapGecmis/@uye.ID" class="btn btn-success" style="background-color:lightseagreen">KİTAP GEÇMİŞİ</a></td>
</tr>

    }
</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))
<a href="/Uye/UyeEkle/" class="btn btn-primary">Yeni Üye Ekle</a>

BiletAl/Views/Uye/UyeEkle.cshtml
@model BiletAl.Models.Entity.TBLUYELER
@{
    ViewBag.Title = "UyeEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        <label>Üye Adı</label>
        @*<input type="text" class="form-control" name="PERSONEL" />*@
        @Html.TextBoxFor(x => x.AD, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.AD, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <label>Üye Soyadı</label>
        @*<input type="text" class="form-control" name="PERSONEL" />*@
        @Html.TextBoxFor(x => x.SOYAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.SOYAD, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <label>Mail Adresi</label>
        @*<input type="text" class="form-control" name="PERSONEL" />*@
        @Html.TextBoxFor(x => x.MAIL, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.MAIL, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <label>Kullanıcı Adı</label>
        @*<input type="text" class="form-control" name="PERSONEL" />*@
        @Html.TextBoxFor(x => x.KULLANICIADI, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.KULLANICIADI, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <label>Şifre</label>
        @*<input type="text" class="form-control" name="PERSONEL" />*@
        @Html.TextBoxFor(x => x.SIFRE, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.SIFRE, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <label>Fotoğraf Linki</label>
        @*<input type="text" class="form-control" name="PERSONEL" />*@
        @Html.TextBoxFor(x => x.FOTOGRAF, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.FOTOGRAF, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <label>Telefon</label>
        @*<input type="text" class="form-control" name="PERSONEL" />*@
        @Html.TextBoxFor(x => x.TELEFON, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.TELEFON, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <label>Okul</label>
        @*<input type="text" class="form-control" name="PERSONEL" />*@
        @Html.TextBoxFor(x => x.OKUL, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.OKUL, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info" id="Btn1">Üye Ekle</button>

    </div>
</form>

BiletAl/Views/Uye/UyeGetir.cshtml
@model BiletAl.Models.Entity.TBLUYELER

@{
    ViewBag.Title = "UyeGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}



@using (Html.BeginForm("UyeGuncelle", "Uye", FormMethod.Post))
{
    <div style="margin-bottom:15px;"></div>
    <div class="form-group">
        @Html.LabelFor(k => k.ID)
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        <br />
        @* @Html.LabelFor(k => k.AD)*@
        <label>Üye Adı</label>
        @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
        <br />
        <label>Üye Soyadı</label>
        @Html.TextBoxFor(k => k.SOYAD, new { @class = "form-control" })
        <br />
        <label>Kullanıcı Adı</label>
        @Html.TextBoxFor(k => k.KULLANICIADI, new { @class = "form-control" })
        <br />
        <label>Şifre</label>
        @Html.TextBoxFor(k => k.SIFRE, new { @class = "form-control" })
        <br />
        <label>Mail Adresi</label>
        @Html.TextBoxFor(k => k.MAIL, new { @class = "form-control" })
        <br />
        <label>Üye Okulu</label>
        @Html.TextBoxFor(k => k.OKUL, new { @class = "form-control" })
        <br />
        <label>Telefon</label>
        @Html.TextBoxFor(k => k.TELEFON, new { @class = "form-control" })
        <br />
        <label>Fotoğraf Linki</label>
        @Html.TextBoxFor(k => k.FOTOGRAF, new { @class = "form-control" })
        <br />


    </div>
    <div>
        <button class="btn btn-warning">GÜNCELLE</button>
    </div>
}

BiletAl/Views/Uye/UyeKitapGecmis.cshtml
@using BiletAl.Models.Entity
@model List<TBLHAREKET>
@{
    ViewBag.Title = "UyeKitapGecmis";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Üye: @ViewBag.u1</h2>
<br />
<table class="table table-danger">
    <tr>
        <th>Kitap Adı</th>
        <th>Personel</th>
        <th>Alış Tarihi</th>
        <th>İade Tarihi</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.TBLKITAP.AD</td>
            <td>@x.TBLPERSONEL.PERSONEL</td>
            <td>@Convert.ToDateTime(x.ALISTARIH).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(x.UYEGETIRTARIH).ToString("dd/MM/yyyy")</td>
        </tr>
    }

</table>