BiletAl/ViewModels/BiletAlViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BiletAl.ViewModels
{
    public class BiletAlViewModel
    {
        public List<int> SatilmamisKoltuklar { get; set; }
        public int OtobusID { get; set; }
        
    }
}

BiletAl/Controllers/BiletController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BiletAl.Models.Entity;
using BiletAl.ViewModels;

namespace BiletAl.Controllers
{
    public class BiletController : Controller
    {
        // GET: Bilet
        DBBILETALEntities1 db = new DBBILETALEntities1();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult BiletGoster()
        {
            var biletler = from k in db.TBLBilet select k;
            var otobusIdBiletler = biletler.ToList();
            return View(otobusIdBiletler);
        }

        public ActionResult BiletAl(int otobusID)
        {
            var otobus = db.TBLOtobüs.FirstOrDefault(o => o.OtobusID == otobusID);
            var satilmisKoltuklar = db.TBLBilet.Where(x => x.OtobusID == otobusID).Select(x=>x.KoltukNo).ToList();
            List<int> satilmamisKoltuklar = new List<int>();
           
            for (int i = 1; i <= otobus.KoltukSayisi; i++)
            {
                if (satilmisKoltuklar.Contains(i) == false)
                {
                    satilmamisKoltuklar.Add(i);
                }
            }
            var model = new BiletAlViewModel()
            {
                SatilmamisKoltuklar = satilmamisKoltuklar,
                OtobusID = otobusID
            };
            return View(model);
        }
     
        [HttpPost]
        public ActionResult BiletAl(int otobusID,string yolcuAdi, string yolcuSoyadi, int koltukNo)
        {
            var otobus = db.TBLOtobüs.FirstOrDefault(o => o.OtobusID == otobusID);
            string eposta = Session["Eposta"].ToString();
            var kullanici = db.TBLKullanici.FirstOrDefault(y => y.Eposta == eposta);
            int satilmisBiletAdeti = db.TBLBilet.Where(x => x.OtobusID == otobusID).Count();
            decimal satisFiyati = otobus.AcilisFiyati +
                otobus.AcilisFiyati*((satilmisBiletAdeti - satilmisBiletAdeti % 5) / 5) *0.1m;
            
            var yolcu = new TBLYolcu {

                YolcuAdı = yolcuAdi,
                YolcuSoyadı = yolcuSoyadi,
            };

            db.TBLYolcu.Add(yolcu);

            db.TBLBilet.Add(new TBLBilet { 
                KoltukNo = koltukNo,
                OtobusID=otobusID,
                SatisFiyati=satisFiyati,
                YolcuID=yolcu.YolcuID,
                KullaniciID=kullanici.KullaniciID,
            });
            db.SaveChanges();
            return RedirectToAction("BiletAlBasarili");
        }
        [HttpGet]
        public ActionResult BiletSil()
        {          
            return View();
        }
        [HttpPost]
        public ActionResult BiletSil(int biletID) 
        {
            var bilet = db.TBLBilet.FirstOrDefault(o => o.BiletID == biletID);
            db.TBLBilet.Remove(bilet);
            db.SaveChanges();
            return View();
        }
        public ActionResult BiletAlBasarili()
        {
            return View();
        }
    }
}

BiletAl/Views/Bilet/BiletAl.cshtml
@model BiletAl.ViewModels.BiletAlViewModel

@{
    ViewBag.Title = "BiletAl";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Bilet Satın Al</h2>

<div style="margin-top:15px; background-color:azure; display:block; position:relative;">
    <form class="form-group" action="/Bilet/BiletAl" method="post" class="form-group" style="padding:5px; position:relative;">

        @Html.Hidden("otobusID", Model.OtobusID)
        <div>
            <p style="margin-top:15px;">Yolcu Adı</p>
            <input type="text" id="yolcuAdi" name="yolcuAdi" />
        </div>


        <div>
            <p style="margin-top:15px;">Yolcu Soyadı</p>
            <input type="text" id="yolcusoyadi" name="yolcusoyadi" />
        </div>

        <div style="margin-top:15px;">
            <p style="margin-top:15px;">Koltuk No:</p>
            <select id="koltukNo" name="koltukNo">
                @foreach (var item in Model.SatilmamisKoltuklar)
                {
                    <option value="@item">@item</option>

                }
            </select>
        </div>
        <p style="margin-top:10px;">
            <input type="submit" value="Satın Al" class="btn btn-success" />
        </p>
    </form>
</div>

BiletAl/Views/Bilet/BiletAlBasarili.cshtml
@{
    ViewBag.Title = "BiletAlBasarili";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Bilet Alma Başarıyla Gerçekleştirildi</h2>

BiletAl/Views/Bilet/BiletGoster.cshtml
@using BiletAl.Models.Entity
@model List<TBLBilet>
@*@model BiletAl.Models.Entity.TBLBilet
    @using BiletAl.Models.Entity*@
@{
    ViewBag.Title = "BiletGoster";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>BiletGoster</h2>

@using (Html.BeginForm("BiletGoster", "Bilet", FormMethod.Get))
{
    <div style="margin-top:15px; margin-bottom:15px;">
        <b>Otobüsler: </b> @Html.TextBox("p")
        <input type="submit" value="Ara" />
    </div>
}


<table class="table table-bordered">
    <tr>
        <th>SeferID</th>
        <th>YolcuID</th>
        <th>Satış Fiyatı</th>
        <th>Koltuk Numarası</th>
        <th>Otobüs ID</th>
        <th>Sil</th>
       
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <form action="/Bilet/BiletSil" method="post">

                @Html.Hidden("biletID", k.BiletID)
                <td>@k.BiletID</td>
                <td>@k.YolcuID</td>
                <td>@k.SatisFiyati</td>
                <td>@k.KoltukNo</td>
                <td>@k.OtobusID</td>

                <td>
                    <p style="margin-top:10px;">
                        <input type="submit" value="Sil" class="btn btn-success" />
                    </p>
                </td>
            </form>
        </tr>
    }

</table>

BiletAl/Views/Bilet/BiletSil.cshtml
@{
    ViewBag.Title = "BiletSil";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Bilet Başarıyla Silindi</h2>